### PR TITLE
Extract the superclass BoundsManager from ObjectiveManager

### PR DESCRIPTION
**Pull request by arnaud-m**
- remove the dependency to the objective variable
- save, modify or exchange bounds between solvers

Note : the modification is invisible for end-users.

### CODE REVIEW

**Comment by arnaud-m** [comment]
Hello,

I do not really understand what has failed in the build. 
Tests seem OK.

**Comment by arnaud-m** [comment]
Up ;)

**Comment by cprudhom** [comment]
Please, edit your PR to push it in `develop` branch.
If you didn't move to develop yet, I can help you doing so.

**Comment by cprudhom** [comment]
We discussed that PR by phone, so are we OK that I can delete it and we include it in the package you will provide ?

**Pull request closed without merging**
