### PR TITLE
For resolving #541, allowing the user to change the solver instance

### PR DESCRIPTION
**Pull request by mwahbi**
I propose setSolver

### CODE REVIEW

**Comment by mwahbi** [comment]
Hi Charles, 
So, the final decision is keep the solver final in model. Right? :(

**Comment by cprudhom** [comment]
Exactly. If you inherit from `Model` I can add a protected or package-private constructor with `Solver` in it, but no setter

**Comment by mwahbi** [comment]
@cprudhom inherit from <code>Model</code> will do the job I want, so if that solution suits you it is good for what I want to do. Thanks you!

**Comment by cprudhom** [comment]
Ok, here is how you should do, this deliberately complicate.

```java
// 1. Declare your own Settings which overrides 'initSolver(Model m)'
Settings s = new Settings() {
    @Override
    public Solver initSolver(Model model) {
        return new MySolver(model);
    }
}; 
// Then create the model with the following constructor:
Model model = new Model(new EnvironmentBuilder().fromFlat().build(), "my name", s);
```

Maybe we could consider creating a model builder (but I'm not a big fan of this).

That will be commit soon and part of the next release

**Pull request closed without merging**
