### PR TITLE
making an accurate implementation of PGLNS from Perron et al. CP2004 & updating toStrings

### PR DESCRIPTION
**Pull request by mwahbi**
I think the PGLNS [Perron et al., CP2004] was not accurate, this is an accurate proposition of its implementation.

### CODE REVIEW

**Comment by cprudhom** [comment]
Could you explain a little bit the modification your brought ?

**Comment by mwahbi** [comment]
Hi @cprudhom,
The story is when updating the list of candidates. In the previous implementation the candidate list are not sorted, while the paper says the candidate should be sorted by the impact on the search tree. In the previous implementation candidate is a SortedMap sorted by the keys (vars index). So, one solution is to create a comparator based on the values or just use and array as I proposed. 
I hope it is clear! 
Regards

**Comment by cprudhom** [comment]
Ok, you're right, my bad. `SortedMap` killed me once again :/
I'll push your patch asap.
Thank you for your contribution once again !

**Comment by cprudhom** [comment]
I certainly won't integrate `Solver.toString()` as is, since it is a copy/paste of `Model.toString()` except for decision path.
Where do you call this method ?

**Comment by cprudhom** [comment]
Plus, did you modify RPGLNS too ? Because it does not appear in the patch.

**Comment by mwahbi** [comment]
I can see my modifications on PropagationGuidedNeighborhood, I have 4 files changed, can you see what I proposed as implementation (get rid of SortedMap and use arrays)?

**Comment by cprudhom** [comment]
Yes, I also received 4 files, but `ReversePropagationGuidedNeighborhood` was not in and it extends `PropagationGuidedNeighborhood`.

I updated its code as follow:
```java
@Override
    protected void update(DecisionPath decisionPath) throws ContradictionException {
        while (logSum > fgmtSize && fragment.cardinality() > 0) {
            // 1. pick a variable
            int id = selectVariable();

            // 2. fix it to its solution value
            if (vars[id].contains(bestSolution[id])) {  // to deal with objective variable and related

                mModel.getEnvironment().worldPush();
                vars[id].instantiateTo(bestSolution[id], Cause.Null);
                mModel.getSolver().propagate();
                fragment.clear(id);

                for (int i = 0; i < n; i++) {
                    int ds = vars[i].getDomainSize();
                    if (fragment.get(i)) { // if not frozen until now
                        if (ds == 1) { // if fixed by side effect
                            fragment.clear(i); // set it has fixed
                        } else {
                            int closeness = (int) ((dsize[i] - ds) / (dsize[i] * 1.) * 100);
                            //                            System.out.printf("%d -> %d :%d\n", dsize[i], ds, closeness);
                            if (closeness > 0) {
                                all[i] = closeness; // add it to candidate list
                            }
                        }
                    }
                }
                mModel.getEnvironment().worldPop();
                candidates = IntStream.range(0, n)
                        .filter(i -> fragment.get(i) || all[i] == 0)
                        .boxed()
                        .sorted(Comparator.comparingInt(i -> all[i]))
                        .limit(listSize)
                        .collect(Collectors.toList());
                logSum = 0;
                for (int i = fragment.nextSetBit(0); i > -1 && i < n; i = fragment.nextSetBit(i + 1)) {
                    logSum += Math.log(vars[i].getDomainSize());
                }
            } else {
                fragment.clear(id);
            }

        }
        for (int i = fragment.nextSetBit(0); i > -1 && i < n; i = fragment.nextSetBit(i + 1)) {
            if (vars[i].contains(bestSolution[i])) {
                impose(i, decisionPath);
            }
        }
        mModel.getSolver().propagate();

        logSum = 0;
        for (int i = 0; i < n; i++) {
            logSum += Math.log(vars[i].getDomainSize());
        }
    }

```
If you agree, I push this version.

**Comment by mwahbi** [comment]
Ouuups I didn't change the reverse, I think your changes on reverse are accurate, go on ;)

**Comment by cprudhom** [comment]
Is it the right PR ?

**Comment by cprudhom** [comment]
I mean, we should try to separate the purpose.
I will ignore the last push of the PR and wait until you create a new one with only the modifications related to #541

**Comment by cprudhom** [comment]
I integrated the PR in the master branch.
Feel free to add a new PR related to #541.

**Comment by cprudhom** [comment]
Well, I should be able to get your last commit

**Comment by mwahbi** [comment]
@cprudhom I am not an expert in github, so I don't know how to fix it. You can ignore the my commit untill I figured out how to do it properly, any advise?

**Pull request closed without merging**
