### PR TITLE
Optimize computeTightestPoint & propagate in ParetoMaximizer - fixes #1026

### LINKED ISSUE #1026: Optimize ParetoMaximizer.computeTightestPoint calculation
Currently unnecessary and expensive `Stream.of()`-streams are created and executed in `ParetoMaximizer.computeTightestPoint()` when computing the tightest point with an empty `paretoFront`-list:

[Source:](https://github.com/chocoteam/choco-solver/blob/ee19fcd1e747ae5acab833e307c4fccdcc17b007/solver/src/main/java/org/chocosolver/solver/objective/ParetoMaximizer.java#L133-L167)
```java
    /**
     * Compute tightest point for objective i
     * i.e. the point that dominates DP_i and has the biggest obj_i
     *
     * @param i index of the variable
     */
    private void computeTightestPoint(int i) throws ContradictionException {
        int tightestPoint = Integer.MIN_VALUE;
        int[] dominatedPoint = computeDominatedPoint(i);
        for (int[] sol : paretoFront) {
            int dominates = dominates(sol, dominatedPoint, i);
            if (dominates > 0) {
                int currentPoint = dominates == 1 ? sol[i] : sol[i] + 1;
                if (tightestPoint < currentPoint) {
                    tightestPoint = currentPoint;
                }
            }
        }
        if (tightestPoint > Integer.MIN_VALUE) {
            objectives[i].updateLowerBound(tightestPoint, this);
        }
    }

    /**
     * Compute dominated point for objective i,
     * i.e. DP_i = (obj_1_max,...,obj_i_min,...,obj_m_max)
     *
     * @param i index of the variable
     * @return dominated point
     */
    private int[] computeDominatedPoint(int i) {
        int[] dp = Stream.of(objectives).mapToInt(IntVar::getUB).toArray();
        dp[i] = objectives[i].getLB();
        return dp;
    }
```

### PR DESCRIPTION
**Pull request by jsimomaa**
fixes #1026

### CODE REVIEW

**Review by cprudhom — APPROVED** [review]

**Comment by jsimomaa** [comment]
I tried to reproduce the failing test:
```
Error:  Failures: 
Error:    LNSTest.test1:118->knapsack20:105 expected [8372] but found [7812]
```
I get different outcomes of this test - sometimes it succeeds and sometimes it fails with different found-value 🤔

**Review by cprudhom — DISMISSED** [review]

**Comment by cprudhom** [comment]
I will wait until the improvements are stable before validating and launching the tests

**Comment by jsimomaa** [comment]
> I will wait until the improvements are stable before validating and launching the tests

Yep, I'd say they now are. These changes improved the performance of my case quite significantly.

Please go ahead with the validation and testing, thank you.

**Comment by cprudhom** [comment]
Thank you for your contribution

**Pull request merged**
